### PR TITLE
es6 rewrite

### PR DESCRIPTION
**Pull request by mpal9000**

### CODE REVIEW

**Comment by kof** [comment]
you forgot to gitignore the lib

**Comment by kof** [comment]
src is going to git, lib to npm

**Comment by kof** [comment]
Just realized another problem, test are not gonna work via gh-pages as they reference from node_modules.

The same issue has been solved in jss-examples by copying jss from node_modules, but in this case it would be dirty as its not just examples.

Any suggestions?

**Comment by kof** [comment]
Also I think we need remove jss from devDependencies.

**Comment by mpal9000** [comment]
This is not a solution, but what about removing the online test running completely. When I need to run the tests, I want to run `npm run test` locally. Also with some new tests for server side rendering, you will have to run them on node anyway.

**Comment by kof** [comment]
yeah we def need to change testing, it needs to run in node and browser and we need a CI, so yes, for now lets remove it from running over gh-pages.

**Comment by mpal9000** [comment]
OK.
`jss` cannot be removed from devDependencies, because it is being used in "jss-\*/test/index.html"

**Comment by kof** [comment]
true, latest npm will not install peerDependencies

**Comment by mpal9000** [comment]
Yes, but I think it must be left as is, to hint the user about the compatible version of `jss` (while installing a plugin).

**Comment by mpal9000** [comment]
Another thing wich is a matter of preference, is the removal of bower support and `xpkg`. This will simplify the packaging.

**Comment by kof** [comment]
I would love to remove bower.json but can we do that? People will complain, lots of them are using bower .... whats your suggestion?

**Comment by mpal9000** [comment]
I wish I had stats of bower usage, but my feeling is that it is fading out. I personally use npm only, because anything more than one package manager is overkill for me.

**Comment by mpal9000** [comment]
Also I think that bower users can install directly from github (I'm not sure)

**Comment by kof** [comment]
lets check that out, I am for removing xpkg and bower too.

**Comment by mpal9000** [comment]
Bower users can install from github and also
from http://bower.io/docs/creating-packages/
> While Bower does not directly use main files, they are listed with the commands bower list --json and bower list --paths, so they can be used by build tools.

I think this mean that without a bower.json they can install form github and then their build tool, will work correctly because it will read from package.json instead of bower.json (and maybe its `browser` field instead of `main`). I'm not sure.

**Comment by mpal9000** [comment]
You can point the `browser` field in package.json to "./dist/jss-px.js" and that's what their build tool will include.

**Comment by kof** [comment]
great, lets do this!

**Comment by mpal9000** [comment]
With this change, npm users will also get the file from dist in their bundles. This will probably mess with their source maps, because their build tool will have too import the created source map of the dist file, to the source map of the bundle.

**Comment by kof** [comment]
we need to make npm users use lib ....

**Comment by mpal9000** [comment]
Yes thats the correct link, I'm just not sure if bower users will have a problem with that. Probably they won't, because their build tool will read the current `main` field in package.json and will bundle all required files as normally. The problem is that I don't use bower and I cannot be sure, because maybe there is a slightly different workflow there.

**Comment by kof** [comment]
Just took a look at popular packages here https://github.com/rackt they all don't use bower and don't specify anything special for it

**Comment by mpal9000** [comment]
I can't take that decision. I'm changing now the tests to be able to run `npm run test` instead of open test/index.html. I don't have an open command. Just xdg-open ;-) I'will use https://www.npmjs.com/package/opener

**Comment by kof** [comment]
lets make tests refactoring a separate task, we need to rethink it and make a good solution in one go.

**Comment by mpal9000** [comment]
I think this is very small step and can be done now. It is for cross-compatibility. And we agreed to remove the online tests. So nothing changes. Only two lines in the readmes.

**Comment by mpal9000** [comment]
Do you agree?

**Comment by kof** [comment]
so it will just open those tests in the browser and thats it?

**Comment by mpal9000** [comment]
Yes only that

**Comment by kof** [comment]
We can do that temporarily .... but real thing would be more complicated

**Comment by mpal9000** [comment]
OK, but I think the command would be still useful, mabe with a sub name and also have one command for testing in node and one for testing with phantom(?)

**Comment by mpal9000** [comment]
or jsdom

**Comment by kof** [comment]
jsdom is not an option at least for those which need real browsers ... karma with real browsers is a better fit.

**Comment by mpal9000** [comment]
yeah there are better solutions

**Comment by kof** [comment]
so are we removing bower.json and xpkg?

**Comment by kof** [comment]
Also I think we should add test and dist folder to .npmignore.  Npm users use tools, they don't need dist.

**Comment by kof** [comment]
Ok take a look at what I did in the main repo: https://github.com/jsstyles/jss/commit/6b8fbd840e13a3736bc50642e16055b0511fcac6

This is how we get bower support without anything redudant and without xpkg.

**Comment by mpal9000** [comment]
Why did you remove the test directory? How can I run the tests in node now. I wan't to run them without forking the project somewhere else, but directly from node_modules if needed. Also the dist directory can be useful in some cases in development mode. I can tell my builder to alias the import to the dist/dist.min file (in development) and also to not parse it at all. This will speed up my build times. I do that sometimes for big libraries. Maybe ti can be useful in other ways too. It's only some kbs.

**Comment by kof** [comment]
Normally when you install some module to use it as a dependency you are not running tests. If you want to change the package itself you clone it anyways. Tests are on git, just not in the npm package now.  Post of libs do it same way. I was just to lazy ....

**Comment by kof** [comment]
Not sure reagrding  dist though ... didn't use it for years, wondering who does ... in development to speed up builds webpack for e.g. has an incremental build feature which allows to build changed parts.

**Comment by mpal9000** [comment]
Whatever you want, this is my preference. Many libs keep test dir in npm too. I actually do the dist aliasing above incremental builds with webpack. Not for this library but it doesn't matter.

**Comment by mpal9000** [comment]
I'm saying that the only reason to remove these dirs is some kbs

**Comment by kof** [comment]
yeah but also purity)

**Comment by mpal9000** [comment]
So are you ok if I do the same changes in all plugins?

**Comment by kof** [comment]
https://github.com/rackt/redux/issues/579

**Comment by kof** [comment]
I agree with http://gofore.com/ohjelmistokehitys/stop-using-bower/

I think we need to remove bower.json completely. Because I don't run into issues with plugins and different jss versions in peerDependencies

**Comment by kof** [comment]
It makes it all more complex than I want to maintain. I think bower users should get somewhere a build with all plugins installed.

**Comment by kof** [comment]
Idea: jss-dist repository where we create different builds for all possible use cases including bower support (even if I dislike bower). This way we can remove all dist folders from all other repositories.

**Comment by kof** [comment]
Professional software (in my eyes) will use npm and browserify/webpack anyways. This jss-dist thing would be for semi professional and/or small websites who might consider bower or whatever else.

**Comment by kof** [comment]
Also jss is a tool which solves high scale problems for web applications, its not something people who build single page landing pages will want to use in the first place. So we are targeting more professional devs with sophisticated apps.

**Comment by mpal9000** [comment]
I think bower users won't have a problem if you keep the dist dir at least in github. The point of not having build products in the git repository is valid, but I believe it can be done if there will be a problem with many PRs and diffs.

If it was my project I would remove bower.json, xpkg and have a dist dir at least in the git repo.

I think jss-dist would be a very boring repo to maintain, without a good reason.

**Comment by kof** [comment]
I have already heard that 5 lines of plugins setup  is too much for some people, so jss-dist would make it for them.

Reasons jss-dist or jss-full or something:
- quick setup, all plugins already installed
- different builds
- support for bower, npm and whatever else

Also

**Comment by kof** [comment]
wdyt?

**Comment by kof** [comment]
The only problem I see is that we need to release new jss-dist on every plugin or core change. Not sure how much of maintenance overhead it is.

**Comment by mpal9000** [comment]
I also think you should promote the plugin concept by not creating this monolith build that you are saying.

**Comment by kof** [comment]
If I would deal with developers like you and me only, I would remove all the builds from git and npm. But we might have different targeting groups.

Also we can first drop the dist builds completely and then if we really see complaints jss-full can be introduced. Maybe we are not gonna have those complaints because our users are smarter and use better tools.

**Comment by mpal9000** [comment]
I'm -1 for removing dist completely. Keep it at least in git. At least for now.

**Comment by mpal9000** [comment]
So you can remove the bower.json from the last patch and decide if you want the test and dist dirs in npm.

**Comment by kof** [comment]
The prob is we don't know if someone needs dist or bower.json until we remove it)))

**Comment by kof** [comment]
+1 on complete bower.json removal

**Comment by kof** [comment]
let me tweet about it, lets see what comes out

**Comment by mpal9000** [comment]
ok no problem

**Comment by kof** [comment]
Also we can provide dist versions via some cdn by pushing it before publishing.

**Comment by kof** [comment]
This way bower user can use it from there, redux does it this way

**Comment by mpal9000** [comment]
I will do whatever is needed tomorrow. Just tell me what you have decided. My opinion is above. Maybe you can do it in jss repo and show me the patch (like before).

**Comment by mpal9000** [comment]
Please don't push any changes to the plugin repos or jss-examples until we decide about those PRs, because there are a lot of changes. I think tomorrow they will be all ready.

**Comment by kof** [comment]
ack

**Comment by kof** [comment]
Ok, take a look at my last commit, gitignore and npmignore files.
dist is now part of npm package, but not part of the repo.
cdnjs will take it from dist automatically

**Comment by kof** [comment]
https://github.com/jsstyles/jss/commit/c59598d977fa43a6aae2eacac4e5442b8a1c03ba

**Comment by mpal9000** [comment]
pushed latest updates

**Comment by kof** [comment]
merged!

**Comment by mpal9000** [comment]
Nice! Hoped that logos would show up in the original repos. Do you have any idea? They are at the first line of each readme and in examples->index.html.

**Comment by mpal9000** [comment]
The urls are ok and they are visible in local md preview. But not in github pages. The url is from the jss group page.

**Comment by kof** [comment]
I see why, its because of http ... needs to be https, just fixed that in jss-px

**Comment by mpal9000** [comment]
Oh yeah I see the console error now. Can you make the changes?

**Comment by mpal9000** [comment]
That's one of the reasons that I proposed before to change all urls to https. But I left it for another day!

**Comment by kof** [comment]
I am on it

**Comment by mpal9000** [comment]
All right

**Comment by mpal9000** [comment]
You can also change the repo's description to match the description in package.json and the first h2 in the readme.

**Comment by kof** [comment]
yep will do it in all repos

**Comment by mpal9000** [comment]
the last two are already matched

**Comment by mpal9000** [comment]
In examples->index.html, a "repo" link could be added next to each "source" link.

**Comment by mpal9000** [comment]
Or better next to the plugin title

**Comment by kof** [comment]
true, however examples page is very minimalistic ... at some point it should become a layout, will note it in a separate issue.

**Comment by kof** [comment]
also the links should be on every example page because people might link them directly

**Comment by mpal9000** [comment]
Yes, I wanted to navigate from one plugin to another and couldn't. Only the main repo has the links

**Comment by kof** [comment]
Should be probably more like a tutorial, you start with first example and go to next and next until you finished.

**Comment by kof** [comment]
Examples could also contain some explanation.

**Comment by mpal9000** [comment]
It can be done in many intresting ways. Maybe another day some simple links could be added at least for now.

**Comment by mpal9000** [comment]
The next real change that I would like to add or use is a true separation of the parsing and the dom manipulation logic. A non breaking approach could be, two new repos `jss-core` and `jss-dom` that will be imported in the main `jss` repo. Then users could import only what they needed. I use only the parsing parts of jss for example, but I have to import everything. A breaking approach would be to keep parsing logic in the `jss` repo and move dom manipulation to a new `jss-dom` project.

**Comment by kof** [comment]
Ideally yes, however need to see if the benefit is big enough, the lib is still tiny ...

**Comment by mpal9000** [comment]
There is no limit to tinyness

**Comment by mpal9000** [comment]
It will help also in the progress of the project, because a separation like this will help to add features and controlling the size a little better.

**Comment by kof** [comment]
I think jss core right now is mostly dom independent. Its a very few places where it uses dom. Basically for attach/detach and for linking if linked option is true. In total dom related code is about 3 LOC

**Comment by kof** [comment]
Right now top prio is better documentation, people are still confused.

**Comment by kof** [comment]
Also more examples.

**Comment by mpal9000** [comment]
Yes that's more important

**Comment by kof** [comment]
Also top prio is to find and demonstrate a way of using frameworks like bootstrap with jss. I think there is a good way to do so by converting it to jss via cli.

**Comment by mpal9000** [comment]
Something like this https://www.npmjs.com/package/jss-css could help maybe.

**Comment by mpal9000** [comment]
Have not used it

**Comment by mpal9000** [comment]
But I think something builded from scratch with js styles in mind, would be by far better than a fragile conversion

**Comment by kof** [comment]
https://github.com/jsstyles/jss/issues/83#issuecomment-139899152

**Comment by kof** [comment]
jss2jss converter needs to handle all cases like pseudo selectors and comma separated selectors and siblings and some other stuff... its already using a css parser, it just needs to be smarter and translate things closer to how jss plugins can use it.

**Comment by mpal9000** [comment]
I didn't know about it. Personally I like to avoid a conversion like this and trying to write styles from scratch, to see the real benefits. I also don't use global selectos, but they are nice to have as an option. Finally I also use normal styles in parallel for more static things.

**Comment by kof** [comment]
Yes this is the best case scenario, but I understand people who want to use feature rich libs ... 

Also I see a way how to avoid global selectors but still be able to use something like bootstrap. In this example you don't render bootstrap styles with global selectors, you just use those selectors to access rule props. 

```javascript
import bootstap from 'bootstrap'
export default {
    myButton: {
      ...bootstrap['.btn'],
      color: 'red'
    }
}
```

**Comment by mpal9000** [comment]
True for utilities and more but there are global parts too in bootstrap.

**Comment by mpal9000** [comment]
These global parts are where I use normal css (with pre/post/no-processor), eg. resets, grids etc.

**Comment by kof** [comment]
I think those global parts should not be global in jss. Think of a component which can be used inside of any other page or app. You can't load there your reset) because it will potentially conflict

**Comment by mpal9000** [comment]
I agree but some things like grids and resets are real globals, in a context of an app.

**Comment by mpal9000** [comment]
There some good and specific css libs like normalize, which I don't see why to rewrite it in js.

**Comment by kof** [comment]
The bad thing about it is that you make your component depend on some globally defined stuff. If you take your component and try to use somewhere else - it won't work as expected.

Never say never. At some point you want to use some components written for one app in another app.

Normalization libs are fine. There is just no cost at using them from jss instead of via global css.

**Comment by kof** [comment]
Also if you write lib components like UI lib, which should be used in different applications with potentially different default css expectations - its much more clean to not to touch anything globally.

**Comment by mpal9000** [comment]
I try to have my eyes and ears open and I'm experimenting with js-styles the last few months.

**Pull request merged**
